rules = [
  Disable
  DisableSyntax
  ExplicitResultTypes
  LeakingImplicitClassVal
  NoAutoTupling
  NoValInForComprehension
  OrganizeImports
  ProcedureSyntax
  RemoveUnused
]

// Exclude modules that don't run with default scalaVersion
project.excludePaths = [
  "glob:**/zio-sbt-source/**"
]

Disable {
  ifSynthetic = [
    "scala/Option.option2Iterable"
    "scala/Predef.any2stringadd"
  ]
}

OrganizeImports {
  expandRelative = true
  groupedImports = Merge
  groups = [
    "re:javax?\\.",
    "scala.",
    "*",
    "zio."
  ]
}

RemoveUnused {
  imports = false // handled by OrganizeImports
}
