// A hand-maintained release-drafter.yml - the real-world state of every ZIO-ecosystem repo upgrading
// zio-sbt-ci - must be adopted by the generated workflow under the default (ciEnableReleaseDrafter := true),
// exactly like ci.yml. Regression test for repos such as zio-process whose hand-written copy was
// previously skipped, so the workflow was never generated by default. Disabling the feature
// must still leave a hand-written copy alone.

ThisBuild / name := "Test Project"

val handMaintainedWorkflow = "name: Release Drafter\non:\n  push:\n    branches: [main]\n"

lazy val root = (project in file("."))
  .settings(
    version := "0.1",

    TaskKey[Unit]("writeHandMaintainedWorkflow") := {
      val f = baseDirectory.value / ".github" / "workflows" / "release-drafter.yml"
      IO.write(f, handMaintainedWorkflow)
    },

    TaskKey[Unit]("checkWorkflowAdopted") := {
      val f = baseDirectory.value / ".github" / "workflows" / "release-drafter.yml"
      if (!f.exists) sys.error(s"expected $f to be generated")
      val actual = IO.read(f)
      if (actual == handMaintainedWorkflow || !actual.startsWith("# This file was autogenerated"))
        sys.error(s"expected the hand-maintained $f to be replaced by the generated workflow, got:\n$actual")
    },

    TaskKey[Unit]("checkWorkflowHandMaintainedPreserved") := {
      val f = baseDirectory.value / ".github" / "workflows" / "release-drafter.yml"
      if (!f.exists) sys.error(s"expected the hand-maintained $f to still exist")
      val actual = IO.read(f)
      if (actual != handMaintainedWorkflow)
        sys.error(
          s"expected the hand-maintained $f to be untouched when disabled, but its content changed.\n" +
            s"--- expected ---\n$handMaintainedWorkflow\n--- actual ---\n$actual"
        )
    }
  )
