lazy val root = (project in file("."))
  .settings(
    version        := "0.1",
    projectName    := "ZIO SBT",
    mainModuleName := "test-project",
    projectStage   := ProjectStage.ProductionReady,

    // Recreate the state described in #749: `website/` holds nothing but mdoc output, because
    // the update-readme job committed `website/docs` alongside README.md.
    TaskKey[Unit]("seedMdocOutput") := {
      val docs = baseDirectory.value / "website" / "docs"
      IO.createDirectory(docs)
      IO.write(docs / "index.md", "# generated by mdoc\n")
    }
  )
  .enablePlugins(WebsitePlugin)
