ThisBuild / name := "Test Project"

val handWritten = "version: 2\nupdates: []\n"

lazy val root = (project in file("."))
  .settings(
    version := "0.1",
    TaskKey[Unit]("writeHandWritten") := {
      IO.write(baseDirectory.value / ".github" / "dependabot.yml", handWritten)
    },
    TaskKey[Unit]("checkExists") := {
      val f = baseDirectory.value / ".github" / "dependabot.yml"
      if (!f.exists) sys.error(s"expected $f to be generated")
      if (!IO.read(f).startsWith("# This file was autogenerated")) sys.error(s"expected $f to carry the autogenerated header")
    },
    TaskKey[Unit]("checkAbsent") := {
      val f = baseDirectory.value / ".github" / "dependabot.yml"
      if (f.exists) sys.error(s"expected no $f when ciEnableDependabot is false")
    },
    TaskKey[Unit]("checkHandWrittenPreserved") := {
      val f = baseDirectory.value / ".github" / "dependabot.yml"
      if (!f.exists || IO.read(f) != handWritten) sys.error(s"expected hand-written $f to be untouched when disabled")
    }
  )
