name: Auto approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT" | jq .
      - uses: hmarr/auto-approve-action@v3.2.1
        if: github.actor == 'scala-actions[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - echo "after skipped step"
