name: Auto approve

on: 
  pull_request:
    types: [opened, edited, reopened, review_requested, auto_merge_enabled]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - echo "${{ toJson(github) }}"
      - uses: hmarr/auto-approve-action@v3.2.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
